version: '3'
services:
  youtube-dl-server:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./:/usr/src/app/
      # When developing, uncomment these lines
      # - ./youtube-dl-server.py:/usr/src/app/youtube-dl-server.py
      # - ./index.html:/usr/src/app/index.html
    network_mode: host
